### ISSUE TITLE
Declare explicit dependency on django-chartflo

### ISSUE THREAD

**Issue by brylie** [synw/django-mptt-graph#1]
As was discussed in the [django-chartflo roadmap issue](https://github.com/synw/django-chartflo/issues/3#issuecomment-323711988), this package should remain separate from django-chartflo. In order to use django-chartflo as a dependency, this chart should explicitly reference django-chartflo (e.g. in a requirements.txt).

Add a requirements.txt, or the equivalent for PIP packaging, that references django-chartflo as a dependency of this project.

**Comment by synw** [comment]
I added a `requirements.txt` file. The setup.py is here but not used yet as `django-chartflo` was not yet packaged. I must admit that this team of modules got a bit neglected since a while. Time to update all this and make it more usable

**Comment by synw** [comment]
It looks like some Django 2 checks has to be made as well to ensure compatibility #2 . Working on it
